### ISSUE TITLE
Sharing ROIs across sessions

### ISSUE THREAD

**Issue by QNeuron** [yves-weissenberger/Multiphoton-Toolbox#13]
Hi,

I used the classifier with the default parameters, and it creates different ROI masks for different files. In my case, all the data is collected in one session from the same area, so the files in the same folder should share the same ROI mask. I think the function share_roi_info.py should do it, but I run into an error (see after). My question is twofold : can I tell the run_roi_finder.py to apply the same ROI mask to all files, and if not, what's wrong with the share_roi_info.py ?

error :
(base) D:\>python D:\Work\Code\gitDev\twoptb\twoptb\ROIs\share_roi_info.py D:\Wo
rk\Data\twopi\rawFerret\Nala2\processed\Nala2_area04\Nala2_area04.h5
C:\Users\dpag0680\AppData\Local\Continuum\anaconda2\lib\site-packages\h5py\__ini
t__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `
float` to `np.floating` is deprecated. In future, it will be treated as `np.floa
t64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "D:\Work\Code\gitDev\twoptb\twoptb\ROIs\share_roi_info.py", line 69, in <
module>
    with h5py.File(hdf_path,'a',libver='latest') as hdf:
NameError: name 'hdf_path' is not defined

S

**Comment by yves-weissenberger** [comment]
This option is currently not included and it runs via the share_roi_info command. There was just a minor typo as far as I could tell. Let me know if current push fixes the problem

**Comment by QNeuron** [comment]
Works like a charm. Thanks
