### ISSUE TITLE
Error message during loading h5 file to ROIs GUI

### ISSUE THREAD

**Issue by sebvasquez91** [yves-weissenberger/Multiphoton-Toolbox#5]
ImportError: No module named sip

**Comment by yves-weissenberger** [comment]
if using on windows with anaconda, uninstall pyqtgraph, reinstinstall the pyqt binary from here [Chris Gohlke](https://www.google.co.uk/search?client=ubuntu&channel=fs&q=chris+grohke&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=teO1WILiA5PY8AfykIzYDQ#channel=fs&q=chris+grohke+windows+binaries&*)
and then reinstall pyqtgraph
