### ISSUE TITLE
load_GRABinfo function failurebecause global name '_todict' is not defined

### ISSUE THREAD

**Issue by samupicard** [yves-weissenberger/Multiphoton-Toolbox#6]
When running 'convert_to_hdf5.py' on tonemapping data, at 96% complete the load_GRABinfo function gives the following error:

> ===== 2018.01.19 14:01:35 =====                                                      
> Traceback (most recent call last):                                                                                        
> File "Documents\twoptb\convert_to_hdf5.py", line 127, in <module>                                                         convert_day_data_to_hdf5(base_path)                                                                                   
> File "Documents\twoptb\convert_to_hdf5.py", line 107, in convert_day_data_to_hdf5                                         session_ID=session_ID)                                                                                                
> File "C:\Users\mert3628\Documents\twoptb\file_management\load_images.py", line 115, in add_raw_series                     
> File, allSame, GRABinfo, stimattrs = load_tiff_series(Dir)                                                            
> File "C:\Users\mert3628\Documents\twoptb\file_management\load_images.py", line 72, in load_tiff_series                    GRABinfo = load_GRABinfo(matfile)                                                                                     File "C:\Users\mert3628\Documents\twoptb\util.py", line 37, in load_GRABinfo                                              dict[strg] = _todict(elem)                                                                                          
> NameError: global name '_todict' is not defined

**Comment by yves-weissenberger** [comment]
solved
