### ISSUE TITLE
same issue, now with _tolist

### ISSUE THREAD

**Issue by samupicard** [yves-weissenberger/Multiphoton-Toolbox#7]
===== 2018.01.19 16:01:04 =====                                                      Traceback (most recent call last):                                                                                        File "Documents\twoptb\convert_to_hdf5.py", line 127, in <module>                                                         convert_day_data_to_hdf5(base_path)                                                                                   File "Documents\twoptb\convert_to_hdf5.py", line 107, in convert_day_data_to_hdf5                                         session_ID=session_ID)                                                                                                File "C:\Users\mert3628\Documents\twoptb\file_management\load_images.py", line 115, in add_raw_series                     File, allSame, GRABinfo, stimattrs = load_tiff_series(Dir)                                                            File "C:\Users\mert3628\Documents\twoptb\file_management\load_images.py", line 72, in load_tiff_series                    GRABinfo = load_GRABinfo(matfile)                                                                                     File "C:\Users\mert3628\Documents\twoptb\util.py", line 37, in load_GRABinfo                                              dictA[strg] = _todict(elem)                                                                                           File "C:\Users\mert3628\Documents\twoptb\util.py", line 55, in _todict                                                    d[strg] = _todict(elem)                                                                                               File "C:\Users\mert3628\Documents\twoptb\util.py", line 57, in _todict                                                    d[strg] = _tolist(elem)                                                                                             NameError: global name '_tolist' is not defined

**Comment by yves-weissenberger** [comment]
solved
