### ISSUE TITLE
ROI drawer not responsive

### ISSUE THREAD

**Issue by samupicard** [yves-weissenberger/Multiphoton-Toolbox#9]
ROI drawer GUI becomes unresponsive at times during video playing, especially when increasing rolling average / spatial smoothing and panning/zooming at the same time. Only way to overcome is to close python completely - no error messages appear.

Issue pops up in windows on a large D drive, even when barely anything else is running in the background. Loading the stack into RAM doesn't solve the issue.

Seems to be a graphics buffering issue or sth like that - related to frame playback rate?

**Comment by yves-weissenberger** [comment]
go into ./ROIs/PyQtGraph_ROI_Drawer.py and reduce framerate. Do this by setting self.IFI to a larger value, setting to 20 solves the problem.
